#切片,取字符串一部分
name="abcdef"
print(name[0:3])
print(name[2:])
print(name[2])
print(name[:3])
#可以越界不报错
print(name[:8])
#注意下面这个
print(name[2:9:7])
print(name[:5])
#从0开始，每两步截取一个字符串
print(name[::2])
#截取末尾两串
print(name[-2:])
#字符串的逆序
print(name[::-1])
print(name[-4:-1])